### PR TITLE
Start a design document for LibreHQ

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by kfogel** [comment]
Flagged all three of you for review because this document contains some core design decisions.  Whoever reads it first can merge it to `master`.  We will not consider the merge to necessarily mean agreement on every design decision :-).

**Comment by frankduncan** [comment]
A few questions:

1. Why use the domain name rather than directory structure?  This pull would be ```http://pulls.OpenTechStrategies.github.com/librehq-core/1``` which feels wrong to me.  You can make the case that pulls would be a subset of "code.ots.gh.com", but you'd still have "issues.ots.gh.com" and "wiki.ots.gh.com".  I like that github goes from left to right with most generic to most specific.  I also like that for a given org, the different services that gh provides are lumped by product, and that seems like a natural fit for a set of open source services

1. There's no org vs user on the project plan for now, so maybe we should add some kind of "phase" notation to this document for things that aren't yet implemented?

1. Do you want me to add a section about code design (how the submodules are set up)?

1. I think I disagree with the username strategy.  If the service were to become popular, there becomes a land grab on names.  This isn't an issue on a site where you make up your username, but it is a large issue on a place like twitter/facebook/domainnames/professional settings where people base their username on their real name or real organization.  Using email address is better because you a) get a username/domain tuple for free, b) the land grab is someone else's problem, and c) people who use places like amazon, facebook, and their email service are used to using their email as the login, so they don't have to remember yet another login that may or may not match the rest.

**Comment by frankduncan** [comment]
As an addendum to 4, the way facebook/webhosting services solve this is by giving you an id that works out of the gate, and then you can later try to find a more descriptive name if you choose.  Amazon does this too, kind of, by uniquely having item ids, then the description comes after the id in the url.  So in that situation, you'd have something like ```http://librehq.com/5128244/OpenTechStrategies/wikis/NewWorldOrder/```

**Comment by kfogel** [comment]
Thanks, Frank.  When I get a chance I will incorporate this feedback (think I agree with some of it, not sure I fully agree on all of it, but in any case it needs thoughtful evaluation and I didn't want your comment to go unresponded-to in the meantime).

Yes, please add a section about code design.

**Comment by kfogel** [comment]
I took most of your advice on the URLs, @frankduncan, thanks!  See the new version of that section.

Regarding use of `git submodules`:

I'm okay trying it out.  I've not had great experiences with them, and am not completely sure what the advantage is over just pulling in the necessary repositories/branches with an assembly script that lives in `librehq-core`, but we can change this decision later if we want to anyway.  I guess I just wanted to flag that as "thing that might come up again" so you're not surprised if we revisit it later.

Regarding usernames and identities:

Let's not conflate these three different things:

* The externally-visible signifiers of a user's identity (in our case, that's whatever string shows up as a URL component, and whatever display name the user chooses);
* The token(s) the user uses to log in with (that set could optionally include one or more email addresses, and could include some strings that *also* double as externally-visible signifiers);
* The system's internal unique identifier for the user (this is something the user may or may not ever see, but the point is it doesn't change no matter what else changes about the user -- it's like a customer's account number at a bank).

This division is written up well in [The Tripartite Identity Pattern](http://habitatchronicles.com/2008/10/the-tripartite-identity-pattern/), by the way.

The land-grab issue is in the "nice problems to have" department :-).  There are various mitigation strategies available, for example: inactive and never-used accounts get swept or are conditionally available to be claimed; requiring some ugly component to the externally-visible name (e.g., you can't get plain "jrandom", you can only get "jrandom01" or "jrandom02" etc).  I'm not sure we need mitigation strategies to start out with, but we can implement them if we need them.

**Comment by kfogel** [comment]
I've only skimmed the submodules section, by the way.  However, I'm fine with merging this to `master` and then working from there.  It's early in the project and changing course on something like that would be easy.

**Comment by frankduncan** [comment]
I'm fine merging, but two followups:

1. I'm creating a user table with id (for row_id), token (for cross service account, in case various services don't play well with id), username, password, and email.  Probably just going to use a GUID for token
2. Interestingly enough, I couldn't easily get MediaWikiFarm to work with subdirectory structure, but it works out of the box with subdomain structure, so our initial prototype push will most likely do what you originally outlined.

If both of those sound good, go ahead and merge (or comment and I'll merge)

**Comment by frankduncan** [comment]
Re: submodules

If there's anything that jumped out at you as challenging to use, that would be good information to have as I set it up.  However, there's definitely no problem to going a different way with this.  I could see either via something like pipenv/package management where you just need to have your development system configured correctly (and for production, we use pipenv with tags after we release subservices), or a configured script that you tell it where to find the services.  Submodules were just the easiest way to satisfy "it's really easy if the service were just a subdirectory, and I don't want them to be in the same repository."  I have no particular allegiance to them.

**Comment by kfogel** [comment]
In [chat](https://chat.opentechstrategies.com/#narrow/stream/38-LibreHQ/subject/Checkins/near/58669) I've asked what you meant by "in case various services don't play well with id"; answer can be here or there.

**Comment by kfogel** [comment]
Np re using subdomain for now, but we should figure out if there's a reason MediaWiki farm prefers that -- it might be a reason we need to take into account too.

FWIW, I had thought that if we *did* decide to go back to subdomains for anything, it would have more likely been username, since doing that suggests an obvious and easily scaleable sharding strategy (as user base grows, just spread users across more machines, based on username).  Going to subdomains based on service instead of username would feel weird, but I suspect there are issues I haven't fully grokked here.  At some point soon we'll want to have a call with James about this, I think; he's likely to have good input.

Whatever we do, we want it finalized before we show instances to anyone outside OTS -- which means we will need to finalize it pretty soon.

**Comment by kfogel** [comment]
Np re continuing with submodules for now.  If it works, it works; if it doesn't, we'll change.

**Pull request merged**
